---
dependencies:
  cloud_firestore: ^3.1.1
  cupertino_icons: ^1.0.4
  firebase_core: ^1.10.6
  fluttertoast: ^8.0.8
  get: ^4.6.1
  http: ^0.13.4
  image_gallery_saver: ^1.7.1
  import_sorter: ^4.6.0
  logger: ^1.1.0
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  qr_flutter: ^4.0.0
  flutter:
    sdk: flutter
description: Digital Solution for Bussiness
dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.16.0 <3.0.0"
flutter:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
  uses-material-design: true
name: pay_qr
publish_to: none
version: 1.0.0+1
