---
dependencies:
  cached_network_image: ^3.2.1
  camera: ^0.9.7+1
  cloud_firestore: ^3.1.17
  contacts_service: ^0.6.3
  csv: ^5.0.1
  cupertino_icons: ^1.0.4
  fancy_shimmer_image: ^2.0.2
  file_saver:
    git: https://github.com/incrediblezayed/file_saver.git
  firebase_analytics: ^9.1.9
  firebase_auth: ^3.3.19
  share_plus: ^4.0.10
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.17
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^1.1.0
  fluttertoast: ^8.0.9
  get: ^4.6.5
  google_nav_bar: ^5.0.6
  http: ^0.13.4
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.5+3
  import_sorter: ^4.6.0
  supercharged: ^2.1.1
  line_icons: ^2.0.1
  logger: ^1.1.0
  mobile_scanner:
    git: https://github.com/ahzam-shahnil/mobile_scanner.git
  modal_bottom_sheet: ^2.0.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  ndialog: ^4.1.1
  octo_image: ^1.0.2
  path: ^1.8.1
  path_provider: ^2.0.9
  pdf: ^3.8.1
  permission_handler: ^9.2.0
  pluto_grid: ^3.1.2
  pluto_grid_export: ^1.0.1
  printing: ^5.9.1
  scan: ^1.6.0
  shimmer: ^2.0.0
  simple_animations: ^4.0.2
  syncfusion_flutter_barcodes: ^20.1.57
  text_scroll: ^0.0.4
  timeago: ^3.2.2
  url_launcher: ^6.1.2
  uuid: ^3.0.6
  flutter_image_compress: ^1.1.0
  jiffy: ^5.0.0
description: Digital Solution for Bussiness
dev_dependencies:
  build_runner: null
  flutter_launcher_icons: ^0.9.3
  flutter_gen_runner: null
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.16.0 <3.0.0"
flutter:
  assets:
    - assets/images/
    - assets/images/onboard_1st/
    - assets/images/onboard_2nd/
    - assets/svgs/
    - assets/tflite/model.tflite
    - assets/tflite/labels.txt
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
  uses-material-design: true
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_wn.png"
flutter_gen:
  integrations:
    flare_flutter: false
    flutter_svg: true
    rive: false
  line_length: 80
  output: lib/gen/
name: pay_qr
publish_to: none
version: 1.0.0+1
